global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'trading-bot-ingestor'
    static_configs:
      - targets: ['ingestor:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'trading-bot-feature-hub'
    static_configs:
      - targets: ['feature-hub:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'trading-bot-model-server'
    static_configs:
      - targets: ['model-server:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'trading-bot-order-router'
    static_configs:
      - targets: ['order-router:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s